services:
  mongodb:
    image: mongo:8.0.11
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    restart: unless-stopped
    
  discord-bot:
    container_name: enmity
    build:
      context: ./apps/bot/
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/discord_bot
    restart: unless-stopped
    develop:
      watch:
        - action: sync+restart
          path: ./apps/bot
          target: /app
    env_file:
      - ./test-bot.env

volumes:
  mongo_data: